export const copy = {
  name: 'Kept',
  skip: 'Skip to content',
  loading: 'One moment…',
  home: {
    eyebrow: 'A resume that keeps up',
    title: 'Send one link. It still tells the truth later.',
    lede: 'Connect GitHub, choose the projects, and say what this version should emphasize. When that work changes, the PDF changes. The link stays the same.',
    make: 'Make a link',
    example: 'See an example',
    stepsTitle: 'How it goes',
    steps: [
      { n: '1', title: 'Connect GitHub', body: 'Kept reads the projects you pick. You choose whether private ones are included.' },
      { n: '2', title: 'Say what this version is for', body: 'A design role and an engineering role can each have their own link and their own brief.' },
      { n: '3', title: 'Share the link', body: 'Anyone with it can open the PDF. You do not send a new file when the work moves on.' },
    ],
    trust: 'Project files stay where they are. The PDF only has the write-up.',
  },
  nav: {
    links: 'Your links',
    newLink: 'New link',
    disconnect: 'Disconnect',
    make: 'Make a link',
    login: 'Log in',
    signIn: 'Sign in',
    signOut: 'Sign out',
  },
  auth: {
    loginTitle: 'Log in',
    loginLede: 'Use the email and password for your Kept account.',
    signInTitle: 'Sign in',
    signInLede: 'Create your Kept account. A short code will arrive by email so we know it is yours.',
    email: 'Email',
    password: 'Password',
    code: 'Code from your email',
    codeLede: 'Enter the code we sent. It is only a few digits.',
    confirm: 'Confirm',
    notReady: 'Sign-in is not ready on this site yet.',
    mismatch: 'That email or password does not match.',
    exists: 'That email already has an account. Log in instead.',
    weakPassword: 'Use at least 8 characters, and pick a password you have not used everywhere else.',
    badCode: 'That code was not right. Try again.',
    taken: 'That GitHub account is already used with another Kept account.',
  },
  start: {
    title: 'Connect your work',
    lede: 'Kept uses your GitHub projects as the material for the resume. Pick what it is allowed to read.',
    publicTitle: 'Only public projects',
    publicBody: 'Projects anyone can already open.',
    allTitle: 'Public and private projects',
    allBody: 'Also projects only you can see. Their names and a short description can appear on the PDF. The files stay on GitHub, and the reading happens on this computer.',
    connect: 'Connect GitHub',
    practice: 'Try it with sample projects',
    notReady: 'GitHub connection is not ready on this site yet.',
  },
  studio: {
    title: 'Shape this version',
    lede: 'Each link can tell the story a different way. The address will not change after you create it.',
    about: 'About you',
    name: 'Your name',
    line: 'Line under your name',
    email: 'Email',
    place: 'Where you are',
    projects: 'Projects',
    projectsHelp: 'Up to eight. Paused projects and copies of other people’s work are left out.',
    count: 'selected',
    empty: 'No projects showed up. If your work is private, include private projects too.',
    allow: 'Allow private projects',
    private: 'Private',
    role: 'The role this version is for',
    rolePlaceholder: 'Product designer',
    brief: 'How should this version be written?',
    briefHelp: 'Write it as if you were briefing a careful person. Name what to emphasize and what to leave out. This brief belongs to this link only.',
    briefPlaceholder: 'Lead with interface work and the results. Leave out internal tooling. First person. Never mention invoices.',
    create: 'Create my link',
    creating: 'Reading your projects…',
  },
  links: {
    title: 'Your links',
    empty: 'No links yet. The first one takes a few minutes to describe, and then it keeps itself current.',
    open: 'Open',
    updated: 'Updated',
  },
  detail: {
    pdf: 'Your PDF link',
    copy: 'Copy link',
    copied: 'Copied',
    page: 'A page for the same resume',
    check: 'Check for updates',
    checking: 'Checking…',
    save: 'Save this brief',
    saving: 'Saving…',
    remove: 'Remove this link',
    removeHelp: 'The link will stop working.',
    confirm: 'Remove it? People who have the link will not be able to open it.',
    yesRemove: 'Yes, remove it',
    waiting: 'Reading your projects and writing the resume.',
    same: 'You can keep sending this same link.',
    readingPrivate: 'Reading a private project on this computer.',
    privateMissed: 'A private project could not be read on this computer. The rest of the resume is ready.',
  },
  public: {
    preparingTitle: 'Preparing the resume',
    preparing: 'This resume is being prepared.',
    tryAgain: 'Open the link again in a moment.',
    open: 'Open the PDF',
    stays: 'This page stays current when their work changes.',
    missing: 'This link does not exist.',
    home: 'Go to Kept',
  },
  pdf: {
    selectedWork: 'Selected work',
    skills: 'Skills',
    example: 'Example',
    nothingToShow: 'Nothing could be written without including what you asked to leave out.',
  },
  missing: {
    title: 'This page does not exist.',
    home: 'Back home',
  },
  errors: {
    generic: 'Something went wrong. Please try again.',
    githubAgain: 'Please connect GitHub again.',
    signedOut: 'Please start again.',
    githubLimited: 'GitHub is busy right now. Your link still shows the last version.',
    projectMissing: 'One of those projects could not be found.',
    readFailed: 'Your projects could not be read just now. The link still shows the last version.',
    partial: 'One project could not be read. The others are included.',
    chooseProjects: 'Choose at least one project.',
    tooMany: 'Choose up to eight projects.',
    notOnList: 'Choose projects from the list.',
    slowDown: 'Too many tries. Wait a moment and try again.',
    needPrivate: 'GitHub has not allowed private projects yet.',
    notReady: 'GitHub connection is not ready on this site yet.',
    denied: 'GitHub access was not granted.',
    missingLink: 'That link could not be found.',
    nothingYet: 'Those projects did not have enough to write from yet.',
    privateUnread: 'That private project could not be kept.',
    connectWork: 'Connect GitHub before choosing projects.',
    upToDate: 'Already up to date.',
    badBrief: 'That brief is too long to keep.',
    email: 'That email does not look right.',
  },
  reasons: {
    first: 'First version.',
    updated: 'One of your projects was updated.',
    reword: 'Rewritten with your notes.',
    checked: 'Checked for new work.',
    local: 'Read on this computer.',
  },
  notice: {
    saved: 'Saved. Your link stays the same.',
    removed: 'That link has been removed.',
  },
}
