export const copy = {
  name: 'Kept',
  skip: 'Skip to content',
  loading: 'One moment…',
  home: {
    eyebrow: 'A resume that keeps up',
    title: 'Send one link. It still tells the truth later.',
    lede: 'Connect GitHub, choose the projects, and say what this version should emphasize. When that work changes, the PDF changes. The link stays the same.',
    make: 'Make a link',
    guest: 'Try as guest',
    example: 'See an example',
    stepsTitle: 'How it goes',
    steps: [
      { n: '1', title: 'Connect GitHub', body: 'One connection covers public and private projects.' },
      { n: '2', title: 'Say what this version is for', body: 'A design role and an engineering role can each have their own link and their own brief.' },
      { n: '3', title: 'Share the link', body: 'Anyone with it can open the PDF. You do not send a new file when the work moves on.' },
    ],
    trust: 'We follow 0 data retention. Public projects use a hosted Gemma model. Private projects use Gemma on this computer.',
  },
  nav: {
    links: 'Your links',
    newLink: 'New link',
    disconnect: 'Disconnect',
    make: 'Make a link',
    login: 'Log in',
    signIn: 'Sign in',
    signOut: 'Sign out',
    guestLeave: 'Leave guest mode',
  },
  guest: {
    continue: 'Continue as guest',
    banner: 'Guest mode — sample projects for now. Connect GitHub to use your repos, or create an account to keep this link long term.',
    connectGitHub: 'Connect GitHub',
    signUp: 'Create an account',
  },
  auth: {
    loginTitle: 'Log in',
    loginLede: 'Use the email and password you made for Kept.',
    signInTitle: 'Sign in',
    signInLede: 'Use your email and a strong password. We will email you a code.',
    email: 'Email',
    password: 'Password',
    forgot: 'Forgot password?',
    forgotTitle: 'Reset your password',
    forgotLede: 'We will email you a code. Then you can choose a new password.',
    forgotSend: 'Email me a code',
    newPassword: 'New password',
    resetTitle: 'Choose a new password',
    resetLede: 'Enter the code from your email and a new password.',
    backToLogin: 'Back to log in',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    code: 'Code from your email',
    codeLede: 'Enter the code we sent. It is only a few digits.',
    confirm: 'Confirm',
    notReady: 'Sign-in is not ready on this site yet.',
    google: 'Continue with Google',
    or: 'or',
    googleFailed: 'Google could not finish signing you in. Try again.',
    mismatch: 'That email or password does not match.',
    unknownEmail: 'We could not find an account with that email.',
    exists: 'That email already has an account. Log in instead.',
    weakPassword: 'Use at least 15 characters, with a capital letter, a small letter, a number, and a symbol.',
    badCode: 'That code was not right. Try again.',
    taken: 'That GitHub account is already used with another Kept account.',
  },
  start: {
    title: 'Connect your work',
    lede: 'We follow 0 data retention.',
    publicModel: 'Public projects use a hosted Gemma model.',
    privateModel: 'Private projects use Gemma on this computer.',
    both: 'One connection covers public and private projects.',
    publicTitle: 'Only public projects',
    publicBody: 'Projects anyone can already open.',
    allTitle: 'Public and private projects',
    allBody: 'Also projects only you can see. Their names and a short description can appear on the PDF. The files stay on GitHub, and the reading happens on this computer.',
    connect: 'Connect GitHub',
    practice: 'Try it with sample projects',
    guest: 'Continue as guest',
    notReady: 'GitHub connection is not ready on this site yet.',
  },
  studio: {
    title: 'Shape this version',
    lede: 'Each link can tell the story a different way. The address will not change after you create it.',
    about: 'About you',
    name: 'Your name',
    line: 'Line under your name',
    email: 'Email',
    place: 'Where you are',
    education: 'Education',
    educationHelp: 'School, a program, or what you studied. Put each one on its own line.',
    educationPlaceholder: 'Lisbon University, product engineering',
    experience: 'Experience',
    experienceHelp: 'A role, a place, and what you did. Put each one on its own line.',
    experiencePlaceholder: 'Kept, product engineer, 2024',
    edit: 'Edit',
    done: 'Done',
    projects: 'Projects',
    projectsHelp: 'Public, or public and private, starts with every project selected. Open it to leave some out. For a role, the whole write-up is used, not only the title. That choice is sent once and is not kept.',
    leaveSome: 'Leave some out',
    leaveForks: 'Leave out copies',
    hideProjects: 'Hide projects',
    count: 'selected',
    found: 'projects',
    empty: 'No projects showed up. If your work is private, include private projects too.',
    allow: 'Allow private projects',
    private: 'Private',
    copied: 'Copy',
    role: 'The role this version is for',
    rolePlaceholder: 'Product designer',
    brief: 'How should this version be written?',
    briefHelp: 'Write it as if you were briefing a careful person. Name what to emphasize and what to leave out. This brief belongs to this link only.',
    briefPlaceholder: 'Lead with interface work and the results. Leave out internal tooling. First person. Never mention invoices.',
    create: 'Create my link',
    creating: 'Reading your projects…',
  },
  links: {
    title: 'Your links',
    empty: 'No links yet. The first one takes a few minutes to describe, and then it keeps itself current.',
    open: 'Open',
    remove: 'Delete',
    yesRemove: 'Yes, delete',
    updated: 'Updated',
  },
  detail: {
    pdf: 'Your PDF link',
    copy: 'Copy link',
    copied: 'Copied',
    download: 'Download PDF',
    page: 'A page for the same resume',
    check: 'Check for updates',
    checking: 'Checking…',
    save: 'Save this brief',
    saving: 'Saving…',
    remove: 'Remove this link',
    removeHelp: 'The link will stop working.',
    confirm: 'Remove it? People who have the link will not be able to open it.',
    yesRemove: 'Yes, remove it',
    keep: 'Keep it',
    waiting: 'Reading your projects and writing the resume.',
    slow: 'This is taking longer than usual.',
    same: 'You can keep sending this same link.',
    readingPrivate: 'Reading a private project on this computer.',
    privateMissed: 'A private project could not be read on this computer. The rest of the resume is ready.',
  },
  public: {
    preparingTitle: 'Preparing the resume',
    preparing: 'This resume is being prepared.',
    tryAgain: 'Open the link again in a moment.',
    open: 'Open the PDF',
    download: 'Download PDF',
    stays: 'This page stays current when their work changes.',
    missing: 'This link does not exist.',
    home: 'Go to Kept',
  },
  pdf: {
    selectedWork: 'Relevant works',
    skills: 'Skills',
    experience: 'Experience',
    education: 'Education',
    contributions: 'Contributions',
    example: 'Example',
    nothingToShow: 'Nothing could be written without including what you asked to leave out.',
    noneFit: 'None of the selected projects fit this role.',
  },
  missing: {
    title: 'This page does not exist.',
    home: 'Back home',
  },
  errors: {
    generic: 'Something went wrong. Please try again.',
    stillWorking: 'Still working…',
    gaveUp: 'Something went wrong. Refresh the page or come back in a moment.',
    githubAgain: 'Please connect GitHub again.',
    signedOut: 'Please start again.',
    sessionLost: 'Your session timed out. Log in again to load projects.',
    loadingProjects: 'Loading your projects…',
    githubLimited: 'GitHub is busy right now. Your link still shows the last version.',
    projectMissing: 'One of those projects could not be found.',
    readFailed: 'Your projects could not be read just now. The link still shows the last version.',
    partial: 'One project could not be read. The others are included.',
    chooseProjects: 'Choose at least one project.',
    tooMany: 'That is more projects than this link can keep.',
    notOnList: 'Choose projects from the list.',
    slowDown: 'Too many tries. Wait a moment and try again.',
    needPrivate: 'GitHub has not allowed private projects yet.',
    notReady: 'GitHub connection is not ready on this site yet.',
    denied: 'GitHub access was not granted.',
    missingLink: 'That link could not be found.',
    nothingYet: 'Those projects did not have enough to write from yet.',
    privateUnread: 'That private project could not be kept.',
    connectWork: 'Connect GitHub before choosing projects.',
    upToDate: 'Already up to date.',
    badBrief: 'That brief is too long to keep.',
    email: 'That email does not look right.',
  },
  reasons: {
    first: 'First version.',
    updated: 'One of your projects was updated.',
    reword: 'Rewritten with your notes.',
    checked: 'Checked for new work.',
    local: 'Read on this computer.',
  },
  notice: {
    saved: 'Saved. Your link stays the same.',
    removed: 'That link has been removed.',
  },
}
